name: Deploy HTML to Azure App Service

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # This will trigger the workflow on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies that the job will run on an Ubuntu latest environment
    environment: production  # Specifies the environment name for use in deployments

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Uses Azure credentials stored in GitHub secrets

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: sampledhaapps  # Specifies the name of the Azure App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Uses the publish profile from GitHub secrets
        package: .  # Deploys the entire repository to Azure App Service
